name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ cmake

    - name: Clean build directory
      run: |
        rm -rf build

    - name: Configure and build
      run: |
        cmake -S . -B build
        cmake --build build
